name: Despliega Pagina a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clona el repositorio
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
        with:
          node-version: 18

    - name: Hacer el Build y Desplegar
      run: |
        # Configurar Surge.sh
        npm install --global surge

        # Desplegar en Surge.sh
        surge --project ./ --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}